Completed Friendship v1 Specifications
iliebabcenco/ror-social-scaffold pull request #2
Opened 2021-04-30 17:31 UTC by chasscepts

We implemented the following features in this milestone
- We placed a link against all users' names in the users' list.
- The link is not shown on the current user or any of their friend's (both confirmed and pending) names.
- On clicking the link, a friend request is sent to that user and they can see it and any other pending requests on their page. 
- They can choose to accept or reject the request. 
- If they reject the request, it is deleted from the database.
- If they accept the request, it is marked as confirmed.
- The current user can see both their and their friends' posts on their page.

2021-04-30 19:46 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @chasscepts and @iliebabcenco  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] There should be a button to invite user to friendship on both users list page and single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) but the button is only present on the users list page.
* [ ] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) but your posts timeline include posts by non-friend users (i.e users who are not friends)
* [ ] When `User A` sends an invite to `User B` using the `Send Invite` button, the `Accept` and `Reject` button should be available for `User B` but there are no buttons. In other words, a user is not able to see friendship requests. Kindly see to that.


## NICE TO HAVE
* [ ] When `User A` sends a friend request to `User B`, you can replace the _"Send Invite"_ button with a text _"Friend request sent"_

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-05-01 08:35 UTC, chasscepts commented
We have fixed points 1 and 2 raised in the first review. Point 3 was already implemented before we requested for code review. A user can see all pending friend requests when they are on their page. Please see the image below.

![friend request demo](https://thumbs2.imgbox.com/c8/1e/CPpIgLJY_t.png)

2021-05-01 15:08 UTC, SajjadAhmad14 commented on app/views/layouts/application.html.erb
> +        <% end %>
Please move this logic to an halper.

2021-05-01 15:09 UTC, SajjadAhmad14 commented on app/views/layouts/application.html.erb
>        <% if current_user %>
Please move this logic to an halper.

2021-05-01 15:09 UTC, SajjadAhmad14 commented on app/views/users/_user.html.erb
> +    <% end %>
Please move this logic to an halper.

2021-05-01 15:14 UTC, SajjadAhmad14 commented on app/views/users/show.html.erb
> +        <% end %>
Please move this logic to a helper.

2021-05-01 15:45 UTC, SajjadAhmad14 requested changes
# Invalid Request
### **Friendly reminder:** "You should use Git Flow in this project. Please take a step back and go through this [lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) and watch the video in it to understand the flow. Then create a brand new repo with the correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with the correct feature branch. This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!"

## Pull Request should be made from the `feature branch` to the `development` branch and the `feature branch` has some descriptive name.

### Happy Coding ☺️

## You can always connect with me on slack ( @Sajjad Ahmad ).

2021-05-01 16:10 UTC, closed without merging